### ISSUE TITLE
Connection problem with diag on Samsung S20 Ultra 5G Qualcomm (Connect to MDM)

### ISSUE THREAD

**Issue by LeeTiK** [mobile-insight/mobileinsight-mobile#39]
Android 11 

Good afternoon, to be honest, the question is not entirely about your application, but I hope you can help me.

If you turn on the DM mode on the phone, then 2 com ports of the diag are revealed there and one of them swears at almost all commands, but in the second SDX55M everything is super, and L3 messages go

![image](https://user-images.githubusercontent.com/54438075/110256202-a1293e00-7fa8-11eb-849b-8220fc1edeaf.png)

I use your diag_revealer and the diag connection happens, everything is fine and the commands go through, but apparently to the SM8250, what should I do to connect to the SDX55M, an application such as Signal Guru seems to connect perfectly, I recorded them through the strace utility and they still connect to / dev / diag. Feature I noticed that they have a command headder of 8 bytes, USER_SPACE + 0xFF 0xFF 0xFF 0xFF. In your code, I saw that there is remote_procs, but it is almost everywhere commented out.

![image](https://user-images.githubusercontent.com/54438075/110256302-2ca2cf00-7fa9-11eb-8bd5-4455ff1b016b.png)

P.s Your application does not start for me because when I try to disable SeLinux, my phone reboots, root through Magisk

**Comment by LeeTiK** [comment]
Looking at the diag_mdlog utility, I realized that I needed to access mdm and not msm. It is in mdm that the useful data, tell me your remote_device does not seem to work, I try to set 1, and I try to make a header 8 bytes to the commands, but because of this fd_diag falls
![image](https://user-images.githubusercontent.com/54438075/110364784-44d02800-8055-11eb-828f-2fdfda5e7efe.png)

**Comment by LeeTiK** [comment]
Solved the problem, you have errors in the code remote_dev connection

**Comment by goodsollee** [comment]
@LeeTiK Hi, I'm currently using MobileInsight-6.0 on Samsung S20 Ultra. But it does not work. In detail, the phone reboots when the MobileInsight turns on. I guess that it may the problem of a malfunctioning rooted phone, so I tried installing network signal guru. However, the network signal guru app works well. 
I wonder how did you fix this app to run on the Samsung S20 Ultra. Can you tell me what is the errors in the code remote_dev connection and how to solve them? 

Thanks in advance.

**Comment by Sinclair19** [comment]
> Solved the problem, you have errors in the code remote_dev connection

Hi, could you please share more information of how did you fix the problem in the code remote_dev connection?
I am facing some writing command I/O error and 0kb in log. Thanks in advance
